### ISSUE TITLE
Code Bug

### ISSUE THREAD

**Issue by zhuqunxi** [coursekevin/svise#3]
Dear Kevin,

This project is beneficial for me in my own research. However, I encountered the following problem without changing the core codes. Could you help me solve it? Thanks.

Best,
Qunxi

d = 2
degree = 5
n_reparam_samples = 512
tau = 1e-5
m, dmdt = None, None
input_labels = None
features = SparsePolynomialFeatures(d, degree=degree, input_labels=input_labels)
drift_prior = SparseMultioutputGLM(
    d,
    SparseFeatures=features,
    n_reparam_samples=n_reparam_samples,
    tau=tau,
    train_x=m, # train_x (Tensor, optional): Training states (for initialization)
    train_y=dmdt, # train_y (Tensor, optional): Training state derivatives (for intialization)
    # transform=transform,
)

see the file ---- svise\sde_learning\_sde_prior.py:284, in SparseMultioutputGLM.W(self, value)
--> 284 tmp[:, self.prior.sparse_index] = value
    285 self.__W = tmp.reshape(-1, self.d, self.num_features)

IndexError: The shape of the mask [21] at index 0 does not match the shape of the indexed tensor [512, 42] at index 1

**Comment by coursekevin** [comment]
Hey Qunxi, I'm sorry I don't have enough information here to debug. Can you provide more information on what you're trying to do?

**Comment by zhuqunxi** [comment]
> Hey Qunxi, I'm sorry I don't have enough information here to debug. Can you provide more information on what you're trying to do?

Dear Kevin,

Thank you for your kind reply. When I switch to use the newly downloaded package, the bug disappear. The previously mentioned bug may arise due to my inappropriate changes in the original package. Thanks again for your help.

Best,
Qunxi
