### ISSUE TITLE
doubts about the derivation of the ELBO 

### ISSUE THREAD

**Issue by fangkaiqi** [coursekevin/svise#4]
Dear Kevin,

This project is beneficial for me in my own research. After combining some papers, I still have doubts about the derivation of the ELBO function. One is how the right hand side of the equals sign of equation (7) in the text is transformed into integral form, and the second is how the variational parameter is introduced so as to obtain the ELBO.The three expressions of the ELBO are very ingenious when viewed on their own and can be corresponded to the meanings, but I am unable to push out the inequality positively due to my probably poor understanding of variational inference.

Best,
Kaiqi

**Comment by coursekevin** [comment]
Hi Kaiqi,

I'm glad to hear the repository has been useful! 

I think a good starting place are references [38,39] in the paper. Alternatively, reference [40] Appendix 9.6.1 has a nice derivation. If you have doubts after going through the references, please feel free to email me directly. I'll try and keep the issues in this repository related to the code + numerical studies.

Best,
Kevin
